<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5TVQmA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5TVQmA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG5TVQmA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG5TVQmA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerG5TVQmA\App_KernelProdContainer([
    'container.build_hash' => 'G5TVQmA',
    'container.build_id' => 'bdd1d19e',
    'container.build_time' => 1686301580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5TVQmA');
