<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'registerJS' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/755.6752b871.js',
                '/build/registerJS.65a30c71.js',
            ],
        ],
        'stripe' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/408.4517235e.js',
                '/build/stripe.4831b2bf.js',
            ],
        ],
        'app' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/408.4517235e.js',
                '/build/app.21b3a091.js',
            ],
            'css' => [
                '/build/app.b75294ae.css',
            ],
        ],
        'hello' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/hello.cfaf2250.js',
            ],
        ],
        'uploadedVideo' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/uploadedVideo.5708e834.js',
            ],
        ],
        'register-label-button' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/755.6752b871.js',
                '/build/register-label-button.351810f3.js',
            ],
        ],
        'algolia-autocompleteJS' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/algolia-autocompleteJS.135f71ca.js',
            ],
        ],
        'navBar' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/755.6752b871.js',
                '/build/navBar.093d9c67.js',
            ],
        ],
        'video' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/video.fd58d1e4.js',
            ],
        ],
        'example1' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/example1.f91cd9e5.js',
            ],
        ],
        'example2' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/example2.78adc313.js',
            ],
        ],
        'example3' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/example3.e4457cfb.js',
            ],
        ],
        'example4' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/example4.050db863.js',
            ],
        ],
        'example5' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/example5.6c6e6ea9.js',
            ],
        ],
        'index' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/index.4077a3be.js',
            ],
        ],
        'stripe2' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/539.a8be2a48.js',
                '/build/186.ff8815f4.js',
                '/build/stripe2.6d002626.js',
            ],
        ],
        'register' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/register.e9e0c2bd.css',
            ],
        ],
        'login' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/login.ed641709.css',
            ],
        ],
        'acceuil' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/acceuil.91d0103b.css',
            ],
        ],
        'algolia-autocomplete' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/algolia-autocomplete.31d6cfe0.css',
            ],
        ],
        'base' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/base.366bd41b.css',
            ],
        ],
        'example1CSS' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/example1CSS.b2661dd8.css',
            ],
        ],
        'example2CSS' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/example2CSS.02fd1012.css',
            ],
        ],
        'example3CSS' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/example3CSS.a3e9f854.css',
            ],
        ],
        'example4CSS' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/example4CSS.ab722287.css',
            ],
        ],
        'example5CSS' => [
            'js' => [
                '/build/runtime.188fa053.js',
            ],
            'css' => [
                '/build/example5CSS.45b5efe3.css',
            ],
        ],
    ],
],

]];
