<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO4dys2J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO4dys2J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO4dys2J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO4dys2J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO4dys2J\App_KernelDevDebugContainer([
    'container.build_hash' => 'O4dys2J',
    'container.build_id' => '99c6a9d1',
    'container.build_time' => 1686299137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO4dys2J');
